### ISSUE TITLE
Making the App Responsive and Look Good on Mobile Devices

### ISSUE THREAD

**Issue by MarcoMorawec** [chaudhary27/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by chaudhary27** [comment]
"To ensure proper rendering and touch zooming, add the viewport meta tag" I added this in the head tag of application.html.erb

``` HTML
<meta name="viewport" content="width=device-width, initial-scale=1">


![screenshot_2015-06-28-13-49-44](https://cloud.githubusercontent.com/assets/7951453/8397523/9f39f1da-1d9c-11e5-8e76-3503b8dd7e6d.png)

Let me know how it looks!
```

**Comment by MarcoMorawec** [comment]
@chaudhary27 :+1:
